import type { Knex } from "knex";
import { companyIds, tagIds, videoId } from "../seedIds.js";

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000);

const videoSeeds: Array<[string, string, string, string, number, number, number, number]> = [
  [
    "Fluxo de caixa que não mente",
    tagIds.financeiro,
    companyIds.c1,
    "Como montar um fluxo de caixa semanal simples, com projeção de 13 semanas, para nunca mais ser surpreendido por um mês ruim.",
    18,
    12,
    4.6,
    32,
  ],
  [
    "Precificação: sua margem real",
    tagIds.financeiro,
    companyIds.c1,
    "Calcule o custo verdadeiro do seu produto ou serviço e descubra quanto você precisa cobrar para crescer com lucro.",
    22,
    28,
    4.2,
    19,
  ],
  [
    "Separando PF de PJ de vez",
    tagIds.financeiro,
    companyIds.c1,
    "Pró-labore, distribuição de lucros e reservas: como organizar o dinheiro da empresa e o seu sem culpa.",
    15,
    50,
    4.8,
    27,
  ],
  [
    "Contratando a primeira liderança",
    tagIds.rh,
    companyIds.c2,
    "O processo completo para sair do 'faço tudo sozinho' e contratar alguém que realmente tira peso das suas costas.",
    27,
    80,
    3.9,
    15,
  ],
  [
    "Feedback que não vira briga",
    tagIds.rh,
    companyIds.c2,
    "Estrutura de conversas difíceis com o time, com roteiro pronto e exemplos de situações reais.",
    19,
    15,
    4.4,
    22,
  ],
  [
    "Cultura em empresa pequena",
    tagIds.rh,
    companyIds.c2,
    "Como definir valores que não ficam só no quadro da parede e usá-los para contratar e demitir.",
    24,
    95,
    4.1,
    11,
  ],
  [
    "Posicionamento antes do anúncio",
    tagIds.marketing,
    companyIds.c3,
    "Por que investir em tráfego sem posicionamento queima dinheiro — e como definir o seu em uma tarde.",
    31,
    35,
    4.7,
    38,
  ],
  [
    "Conteúdo que gera reunião",
    tagIds.marketing,
    companyIds.c3,
    "Um método simples de pauta semanal para transformar audiência em oportunidades comerciais.",
    20,
    60,
    4.0,
    17,
  ],
  [
    "Métricas de marketing que importam",
    tagIds.marketing,
    companyIds.c3,
    "CAC, LTV e payback explicados na prática, com planilha de acompanhamento mensal.",
    26,
    150,
    4.5,
    29,
  ],
  [
    "Mapeando seu processo em 1 folha",
    tagIds.processos,
    companyIds.c4,
    "Técnica de mapeamento rápido para enxergar gargalos e retrabalho na operação do dia a dia.",
    16,
    9,
    3.8,
    8,
  ],
  [
    "Automatizando o operacional",
    tagIds.processos,
    companyIds.c4,
    "Quais tarefas automatizar primeiro e como escolher ferramentas sem virar refém de tecnologia.",
    23,
    40,
    4.3,
    21,
  ],
  [
    "Indicadores de operação",
    tagIds.processos,
    companyIds.c4,
    "Como criar um painel semanal de operação com 5 indicadores que realmente mudam decisões.",
    21,
    72,
    4.6,
    24,
  ],
  [
    "Playbook comercial do zero",
    tagIds.vendas,
    companyIds.c5,
    "Etapas do funil, scripts, objeções e critérios de passagem: o documento que padroniza o seu time.",
    35,
    110,
    4.7,
    41,
  ],
  [
    "Prospecção ativa sem desespero",
    tagIds.vendas,
    companyIds.c5,
    "Rotina diária de prospecção que cabe em 45 minutos e gera pipeline constante.",
    17,
    200,
    4.4,
    33,
  ],
  [
    "Metas e comissionamento",
    tagIds.vendas,
    companyIds.c5,
    "Como desenhar metas justas e um plano de comissão que puxa o resultado sem quebrar o caixa.",
    28,
    18,
    3.6,
    9,
  ],
  [
    "Delegar sem perder o controle",
    tagIds.lideranca,
    companyIds.c2,
    "Níveis de delegação, rituais de acompanhamento e como parar de ser o gargalo da empresa.",
    24,
    130,
    4.5,
    30,
  ],
  [
    "Rituais de gestão semanal",
    tagIds.lideranca,
    companyIds.c4,
    "A agenda do dono: reunião de time, 1:1 e revisão de indicadores em menos de 3 horas por semana.",
    19,
    45,
    4.2,
    16,
  ],
  [
    "Tomando decisões difíceis",
    tagIds.lideranca,
    companyIds.c5,
    "Um framework para decidir com informação incompleta e comunicar a decisão para o time.",
    26,
    88,
    4.8,
    26,
  ],
];

export async function seed(knex: Knex): Promise<void> {
  const videos = videoSeeds.map(
    ([title, tagId, companyId, description, duration, views, rating, ratingsCount], i) => ({
      id: videoId(i + 1),
      tagId,
      row: {
        id: videoId(i + 1),
        title,
        description,
        duration,
        company_id: companyId,
        views,
        rating,
        ratings_count: ratingsCount,
        published_at: daysAgo(5 + i * 12),
      },
    }),
  );

  await knex("videos").insert(videos.map((v) => v.row));
  await knex("video_tags").insert(videos.map((v) => ({ video_id: v.id, tag_id: v.tagId })));
}
