/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AlunoBibliotecaRouteImport } from './routes/aluno.biblioteca'
import { Route as AlunoComunidadeRouteImport } from './routes/aluno.comunidade'
import { Route as AlunoEmpresasRouteImport } from './routes/aluno.empresas'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoTeiaRouteImport } from './routes/aluno.teia'
import { Route as MentorIndexRouteImport } from './routes/mentor.index'
import { Route as MentorAlunosRouteImport } from './routes/mentor.alunos'
import { Route as MentorComunidadeRouteImport } from './routes/mentor.comunidade'
import { Route as MentorConteudoRouteImport } from './routes/mentor.conteudo'
import { Route as MentorFinanceiroRouteImport } from './routes/mentor.financeiro'
import { Route as MentorLpRouteImport } from './routes/mentor.lp'
import { Route as MentorStaffRouteImport } from './routes/mentor.staff'
import { Route as MentorTeiaRouteImport } from './routes/mentor.teia'
import { Route as MentorUsuariosRouteImport } from './routes/mentor.usuarios'
import { Route as RedefinirSenhaTokenRouteImport } from './routes/redefinir-senha.$token'
import { Route as AlunoEmpresaIdRouteImport } from './routes/aluno.empresa.$id'
import { Route as AlunoTeiaMapaRouteImport } from './routes/aluno.teia_.mapa'
import { Route as AlunoVideoIdRouteImport } from './routes/aluno.video.$id'
import { Route as MentorAlunoIdRouteImport } from './routes/mentor.aluno.$id'
import { Route as MentorTeiaMapaRouteImport } from './routes/mentor.teia_.mapa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoBibliotecaRoute = AlunoBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoComunidadeRoute = AlunoComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoEmpresasRoute = AlunoEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoTeiaRoute = AlunoTeiaRouteImport.update({
  id: '/teia',
  path: '/teia',
  getParentRoute: () => AlunoRoute,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorRoute,
} as any)
const MentorAlunosRoute = MentorAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => MentorRoute,
} as any)
const MentorComunidadeRoute = MentorComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => MentorRoute,
} as any)
const MentorConteudoRoute = MentorConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => MentorRoute,
} as any)
const MentorFinanceiroRoute = MentorFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => MentorRoute,
} as any)
const MentorLpRoute = MentorLpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => MentorRoute,
} as any)
const MentorStaffRoute = MentorStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => MentorRoute,
} as any)
const MentorTeiaRoute = MentorTeiaRouteImport.update({
  id: '/teia',
  path: '/teia',
  getParentRoute: () => MentorRoute,
} as any)
const MentorUsuariosRoute = MentorUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => MentorRoute,
} as any)
const RedefinirSenhaTokenRoute = RedefinirSenhaTokenRouteImport.update({
  id: '/redefinir-senha/$token',
  path: '/redefinir-senha/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoEmpresaIdRoute = AlunoEmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoTeiaMapaRoute = AlunoTeiaMapaRouteImport.update({
  id: '/teia_/mapa',
  path: '/teia/mapa',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoVideoIdRoute = AlunoVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => AlunoRoute,
} as any)
const MentorAlunoIdRoute = MentorAlunoIdRouteImport.update({
  id: '/aluno/$id',
  path: '/aluno/$id',
  getParentRoute: () => MentorRoute,
} as any)
const MentorTeiaMapaRoute = MentorTeiaMapaRouteImport.update({
  id: '/teia_/mapa',
  path: '/teia/mapa',
  getParentRoute: () => MentorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/aluno/biblioteca': typeof AlunoBibliotecaRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/empresas': typeof AlunoEmpresasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/teia': typeof AlunoTeiaRoute
  '/mentor/alunos': typeof MentorAlunosRoute
  '/mentor/comunidade': typeof MentorComunidadeRoute
  '/mentor/conteudo': typeof MentorConteudoRoute
  '/mentor/financeiro': typeof MentorFinanceiroRoute
  '/mentor/lp': typeof MentorLpRoute
  '/mentor/staff': typeof MentorStaffRoute
  '/mentor/teia': typeof MentorTeiaRoute
  '/mentor/usuarios': typeof MentorUsuariosRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/aluno/': typeof AlunoIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/aluno/empresa/$id': typeof AlunoEmpresaIdRoute
  '/aluno/teia/mapa': typeof AlunoTeiaMapaRoute
  '/aluno/video/$id': typeof AlunoVideoIdRoute
  '/mentor/aluno/$id': typeof MentorAlunoIdRoute
  '/mentor/teia/mapa': typeof MentorTeiaMapaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/aluno/biblioteca': typeof AlunoBibliotecaRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/empresas': typeof AlunoEmpresasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/teia': typeof AlunoTeiaRoute
  '/mentor/alunos': typeof MentorAlunosRoute
  '/mentor/comunidade': typeof MentorComunidadeRoute
  '/mentor/conteudo': typeof MentorConteudoRoute
  '/mentor/financeiro': typeof MentorFinanceiroRoute
  '/mentor/lp': typeof MentorLpRoute
  '/mentor/staff': typeof MentorStaffRoute
  '/mentor/teia': typeof MentorTeiaRoute
  '/mentor/usuarios': typeof MentorUsuariosRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/aluno': typeof AlunoIndexRoute
  '/mentor': typeof MentorIndexRoute
  '/aluno/empresa/$id': typeof AlunoEmpresaIdRoute
  '/aluno/teia/mapa': typeof AlunoTeiaMapaRoute
  '/aluno/video/$id': typeof AlunoVideoIdRoute
  '/mentor/aluno/$id': typeof MentorAlunoIdRoute
  '/mentor/teia/mapa': typeof MentorTeiaMapaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/aluno/biblioteca': typeof AlunoBibliotecaRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/empresas': typeof AlunoEmpresasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/teia': typeof AlunoTeiaRoute
  '/mentor/alunos': typeof MentorAlunosRoute
  '/mentor/comunidade': typeof MentorComunidadeRoute
  '/mentor/conteudo': typeof MentorConteudoRoute
  '/mentor/financeiro': typeof MentorFinanceiroRoute
  '/mentor/lp': typeof MentorLpRoute
  '/mentor/staff': typeof MentorStaffRoute
  '/mentor/teia': typeof MentorTeiaRoute
  '/mentor/usuarios': typeof MentorUsuariosRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/aluno/': typeof AlunoIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/aluno/empresa/$id': typeof AlunoEmpresaIdRoute
  '/aluno/teia_/mapa': typeof AlunoTeiaMapaRoute
  '/aluno/video/$id': typeof AlunoVideoIdRoute
  '/mentor/aluno/$id': typeof MentorAlunoIdRoute
  '/mentor/teia_/mapa': typeof MentorTeiaMapaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/checkout'
    | '/login'
    | '/mentor'
    | '/recuperar-senha'
    | '/aluno/biblioteca'
    | '/aluno/comunidade'
    | '/aluno/empresas'
    | '/aluno/perfil'
    | '/aluno/teia'
    | '/mentor/alunos'
    | '/mentor/comunidade'
    | '/mentor/conteudo'
    | '/mentor/financeiro'
    | '/mentor/lp'
    | '/mentor/staff'
    | '/mentor/teia'
    | '/mentor/usuarios'
    | '/redefinir-senha/$token'
    | '/aluno/'
    | '/mentor/'
    | '/aluno/empresa/$id'
    | '/aluno/teia/mapa'
    | '/aluno/video/$id'
    | '/mentor/aluno/$id'
    | '/mentor/teia/mapa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/recuperar-senha'
    | '/aluno/biblioteca'
    | '/aluno/comunidade'
    | '/aluno/empresas'
    | '/aluno/perfil'
    | '/aluno/teia'
    | '/mentor/alunos'
    | '/mentor/comunidade'
    | '/mentor/conteudo'
    | '/mentor/financeiro'
    | '/mentor/lp'
    | '/mentor/staff'
    | '/mentor/teia'
    | '/mentor/usuarios'
    | '/redefinir-senha/$token'
    | '/aluno'
    | '/mentor'
    | '/aluno/empresa/$id'
    | '/aluno/teia/mapa'
    | '/aluno/video/$id'
    | '/mentor/aluno/$id'
    | '/mentor/teia/mapa'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/checkout'
    | '/login'
    | '/mentor'
    | '/recuperar-senha'
    | '/aluno/biblioteca'
    | '/aluno/comunidade'
    | '/aluno/empresas'
    | '/aluno/perfil'
    | '/aluno/teia'
    | '/mentor/alunos'
    | '/mentor/comunidade'
    | '/mentor/conteudo'
    | '/mentor/financeiro'
    | '/mentor/lp'
    | '/mentor/staff'
    | '/mentor/teia'
    | '/mentor/usuarios'
    | '/redefinir-senha/$token'
    | '/aluno/'
    | '/mentor/'
    | '/aluno/empresa/$id'
    | '/aluno/teia_/mapa'
    | '/aluno/video/$id'
    | '/mentor/aluno/$id'
    | '/mentor/teia_/mapa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaTokenRoute: typeof RedefinirSenhaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/biblioteca': {
      id: '/aluno/biblioteca'
      path: '/biblioteca'
      fullPath: '/aluno/biblioteca'
      preLoaderRoute: typeof AlunoBibliotecaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/comunidade': {
      id: '/aluno/comunidade'
      path: '/comunidade'
      fullPath: '/aluno/comunidade'
      preLoaderRoute: typeof AlunoComunidadeRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/empresas': {
      id: '/aluno/empresas'
      path: '/empresas'
      fullPath: '/aluno/empresas'
      preLoaderRoute: typeof AlunoEmpresasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/teia': {
      id: '/aluno/teia'
      path: '/teia'
      fullPath: '/aluno/teia'
      preLoaderRoute: typeof AlunoTeiaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/alunos': {
      id: '/mentor/alunos'
      path: '/alunos'
      fullPath: '/mentor/alunos'
      preLoaderRoute: typeof MentorAlunosRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/comunidade': {
      id: '/mentor/comunidade'
      path: '/comunidade'
      fullPath: '/mentor/comunidade'
      preLoaderRoute: typeof MentorComunidadeRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/conteudo': {
      id: '/mentor/conteudo'
      path: '/conteudo'
      fullPath: '/mentor/conteudo'
      preLoaderRoute: typeof MentorConteudoRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/financeiro': {
      id: '/mentor/financeiro'
      path: '/financeiro'
      fullPath: '/mentor/financeiro'
      preLoaderRoute: typeof MentorFinanceiroRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/lp': {
      id: '/mentor/lp'
      path: '/lp'
      fullPath: '/mentor/lp'
      preLoaderRoute: typeof MentorLpRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/staff': {
      id: '/mentor/staff'
      path: '/staff'
      fullPath: '/mentor/staff'
      preLoaderRoute: typeof MentorStaffRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/teia': {
      id: '/mentor/teia'
      path: '/teia'
      fullPath: '/mentor/teia'
      preLoaderRoute: typeof MentorTeiaRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/usuarios': {
      id: '/mentor/usuarios'
      path: '/usuarios'
      fullPath: '/mentor/usuarios'
      preLoaderRoute: typeof MentorUsuariosRouteImport
      parentRoute: typeof MentorRoute
    }
    '/redefinir-senha/$token': {
      id: '/redefinir-senha/$token'
      path: '/redefinir-senha/$token'
      fullPath: '/redefinir-senha/$token'
      preLoaderRoute: typeof RedefinirSenhaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/empresa/$id': {
      id: '/aluno/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/aluno/empresa/$id'
      preLoaderRoute: typeof AlunoEmpresaIdRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/teia_/mapa': {
      id: '/aluno/teia_/mapa'
      path: '/teia/mapa'
      fullPath: '/aluno/teia/mapa'
      preLoaderRoute: typeof AlunoTeiaMapaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/video/$id': {
      id: '/aluno/video/$id'
      path: '/video/$id'
      fullPath: '/aluno/video/$id'
      preLoaderRoute: typeof AlunoVideoIdRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/mentor/aluno/$id': {
      id: '/mentor/aluno/$id'
      path: '/aluno/$id'
      fullPath: '/mentor/aluno/$id'
      preLoaderRoute: typeof MentorAlunoIdRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/teia_/mapa': {
      id: '/mentor/teia_/mapa'
      path: '/teia/mapa'
      fullPath: '/mentor/teia/mapa'
      preLoaderRoute: typeof MentorTeiaMapaRouteImport
      parentRoute: typeof MentorRoute
    }
  }
}

interface AlunoRouteChildren {
  AlunoBibliotecaRoute: typeof AlunoBibliotecaRoute
  AlunoComunidadeRoute: typeof AlunoComunidadeRoute
  AlunoEmpresasRoute: typeof AlunoEmpresasRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoTeiaRoute: typeof AlunoTeiaRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  AlunoEmpresaIdRoute: typeof AlunoEmpresaIdRoute
  AlunoTeiaMapaRoute: typeof AlunoTeiaMapaRoute
  AlunoVideoIdRoute: typeof AlunoVideoIdRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoBibliotecaRoute: AlunoBibliotecaRoute,
  AlunoComunidadeRoute: AlunoComunidadeRoute,
  AlunoEmpresasRoute: AlunoEmpresasRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoTeiaRoute: AlunoTeiaRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  AlunoEmpresaIdRoute: AlunoEmpresaIdRoute,
  AlunoTeiaMapaRoute: AlunoTeiaMapaRoute,
  AlunoVideoIdRoute: AlunoVideoIdRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface MentorRouteChildren {
  MentorAlunosRoute: typeof MentorAlunosRoute
  MentorComunidadeRoute: typeof MentorComunidadeRoute
  MentorConteudoRoute: typeof MentorConteudoRoute
  MentorFinanceiroRoute: typeof MentorFinanceiroRoute
  MentorLpRoute: typeof MentorLpRoute
  MentorStaffRoute: typeof MentorStaffRoute
  MentorTeiaRoute: typeof MentorTeiaRoute
  MentorUsuariosRoute: typeof MentorUsuariosRoute
  MentorIndexRoute: typeof MentorIndexRoute
  MentorAlunoIdRoute: typeof MentorAlunoIdRoute
  MentorTeiaMapaRoute: typeof MentorTeiaMapaRoute
}

const MentorRouteChildren: MentorRouteChildren = {
  MentorAlunosRoute: MentorAlunosRoute,
  MentorComunidadeRoute: MentorComunidadeRoute,
  MentorConteudoRoute: MentorConteudoRoute,
  MentorFinanceiroRoute: MentorFinanceiroRoute,
  MentorLpRoute: MentorLpRoute,
  MentorStaffRoute: MentorStaffRoute,
  MentorTeiaRoute: MentorTeiaRoute,
  MentorUsuariosRoute: MentorUsuariosRoute,
  MentorIndexRoute: MentorIndexRoute,
  MentorAlunoIdRoute: MentorAlunoIdRoute,
  MentorTeiaMapaRoute: MentorTeiaMapaRoute,
}

const MentorRouteWithChildren =
  MentorRoute._addFileChildren(MentorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaTokenRoute: RedefinirSenhaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
